name: udacity-agentic-ai
dependencies:
  - python=3.11
  - pip
  - pip:
      - ipykernel
      - jupyterlab
      - matplotlib
      - json-repair==0.47.1
      - numexpr==2.11.0
      - openai==1.74.0
      - pandas==2.3.0
      - pydantic==2.11.7
      - python-dotenv==1.1.0
